### PR TITLE
Migration for choice fields. Fixes #95

### LINKED ISSUE #95: Unapplied Migrations
PR #92 removed some kwargs from models to silence the migration warnings. Even though the kwargs were unused, Django still detects that the models have changed.

Add Django 1.7 and South migrations for 1.6

### PR DESCRIPTION
**Pull request by damonkelley**

### CODE REVIEW

**Comment by damonkelley** [comment]
ping @ldko @somexpert

**Comment by damonkelley** [comment]
FWIW, the build failed due to a Flake8 error. They have added additional checks that we can ignore. #105 adds those checks to the ignore list.

**Comment by somexpert** [comment]
Yeah I'm not familiar with the errors being shown. I'll have to see what else flake8 added.

**Comment by damonkelley** [comment]
this was rebased on top of #105 and force pushed.

**Pull request merged**
