### PR TITLE
Database Requirements

### LINKED ISSUE #81: Database Requirements
Add a section to the docs regarding database requirements. We should also see about testing this with Postgres and adding a travis configuration if it is compatible.

### PR DESCRIPTION
**Pull request by damonkelley**
Will fix #81 

WIP

I am also going to include a few updates to the docs in this PR.

### CODE REVIEW

**Comment by damonkelley** [comment]
Ok. This should be all wrapped up and ready for review (pending the Travis builds that are in progress at the time of this writing.)

I edited quite a bit of the documentation, so please be sure to give that a look. You can see docs for this branch here: http://django-name.readthedocs.org/en/migrations/. Let me know if any part is confusing or needs more information.

#### What else did you do, Damon?
1. Add database migrations both for South **and** Django 1.7+
2. Added testing environments for Postgres. (tox, travis)
3. Reworked some of the requirements files and dev environment for 2.
4. As I was adding some of the docs, I realized that there was a better way to do the `context_processors` so I consolidated them into a single function.

ping @vphill @somexpert @ldko
cc: @jason-ellis

**Comment by damonkelley** [comment]
BTW. If you decide to pull down this branch locally and give it a whirl, be sure to rebuild the docker image. Some of the requirements have changed.

**Comment by damonkelley** [comment]
@ldko, I have added a note about referring to the Django docs, and test against Django master do not run locally by default  (because they _could_ fail).

**Comment by ldko** [comment]
:+1:

**Pull request merged**
